########################################################################
##                                                                    ##
##               M  a  k  e  f  i  l  e                               ##
##                                                                    ##
##   Makefile to create HTML files from man pages                     ##
##                                                                    ##
##   written by Werner von Bloh                                       ##
##   Potsdam Institute for Climate Impact Research                    ##
##   P.O. Box 60 12 03                                                ##
##   14412 Potsdam/Germany                                            ##
##                                                                    ##
##   Last change: 06.04.2011                                          ##
##                                                                    ##
########################################################################

all:
	(cd man1; $(MAKE))
	(cd man3; $(MAKE))
	(cd man5; $(MAKE))
