.TH lpjdistribute_river 1  "March 10, 2009" "version 3.5.002" "USER COMMANDS"
.SH NAME
lpjdistribute_river \- Submit LoadLeveler jobs for distributed LPJmL simulation with river routing enabled 
.SH SYNOPSIS
.B lpjdistribute_river
[\-class c] njobs [LPJargs ...]
.SH DESCRIPTION
Script creates LPJmL configuration and LoadLeveler job control files and submits the jobs to the LoadLeveler queue. LPJmL grid is distributed according to the settings in the  cru_1901-2003_<nnn>.conf configuration file. Script creates njobs LPJmL configuration files named lpj<nnn>.conf, where <nnn> is the job
number ranging from 0 to njobs-1. Used for the sequential LPJmL code without MPI support. 
.SH OPTIONS
.TP
\-class c
set the LoadLeveler class to which the job will be submitted. Default class is 'short'. Valid classes can be obtained by the
.B llclass
command.
.TP
njobs
set the number of jobs submitted to the LoadLeveler queue. Must be an integer greater than zero.
.TP
LPJargs
set command line arguments for the
.B lpjml
program.
.SH EXAMPLES
.TP
Submit 44 jobs starting from restart file to LoadLeveler class short:
.B lpjdistribute_river
\-class short 44 -DFROM_RESTART
.PP
.SH ENVIRONMENT
.TP
LPJROOT
defines the root directory for LPJmL. The variable has to be defined before calling \fBlpjdistribute\fP.

.SH EXIT STATUS
.B lpjdistribute_river 
returns a zero exit status if LoadLeveler job has been submitted.
Non zero is returned in case of failure.
.SH AUTHOR
Werner von Bloh (Werner.von.Bloh@pik-potsdam.de)

.SH SEE ALSO
lpjml(1), lpjcheck(1), lpjcat(1), cat2bsq(1), output_bsq(1), lpjdistribute(1), llclass(1), llsubmit(1)
